spring:
  application:
    name: note-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/noteService
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
